### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by adamaayala** [startsUp/TrnTable#2]
How do you have Firebase setup for Auth?

**Comment by startsUp** [comment]
I'm using the <a href="https://firebase.google.com/docs/auth/web/custom-auth">custom authentication</a> service that firebase provides. My authentication server implements <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/"> authorization code flow </a> for Spotify and handles the firebase user creation and token generation. It works similary to this <a href="https://firebase.googleblog.com/2016/10/authenticate-your-firebase-users-with.html"> example</a> which implements auth for instagram.
